// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX8KfaN0yFwGihxH5B7bK5IW6-YLUlnL8',
    appId: '1:338914935245:web:45e381aeca633c2ae6c484',
    messagingSenderId: '338914935245',
    projectId: 'citiride-d7743',
    authDomain: 'citiride-d7743.firebaseapp.com',
    storageBucket: 'citiride-d7743.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwCdjrlTEIWqhVjqHActn_u0yvOT_zf2k',
    appId: '1:338914935245:android:6f964ea24c9c3e00e6c484',
    messagingSenderId: '338914935245',
    projectId: 'citiride-d7743',
    storageBucket: 'citiride-d7743.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJdb_kX56R5v_gBt-VbNMligUmBJBVHAQ',
    appId: '1:338914935245:ios:08f3aa704b0fd460e6c484',
    messagingSenderId: '338914935245',
    projectId: 'citiride-d7743',
    storageBucket: 'citiride-d7743.firebasestorage.app',
    iosBundleId: 'com.example.citiride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJdb_kX56R5v_gBt-VbNMligUmBJBVHAQ',
    appId: '1:338914935245:ios:08f3aa704b0fd460e6c484',
    messagingSenderId: '338914935245',
    projectId: 'citiride-d7743',
    storageBucket: 'citiride-d7743.firebasestorage.app',
    iosBundleId: 'com.example.citiride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX8KfaN0yFwGihxH5B7bK5IW6-YLUlnL8',
    appId: '1:338914935245:web:9940a53777a2b1c2e6c484',
    messagingSenderId: '338914935245',
    projectId: 'citiride-d7743',
    authDomain: 'citiride-d7743.firebaseapp.com',
    storageBucket: 'citiride-d7743.firebasestorage.app',
  );
}
